title: Varada Nambiar
logo: "/profile.png?raw=true"
description: Software Developer || Structural Engineer
<a href = "https://theinterviewportal.com/2021/12/18/structural-engineering-software-professional-interview/"> Full Story </a> 


theme: minima
