title: Varada Nambiar # your name (or website title) here
logo: "profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Software Developer || Structural Engineer
  <br><br>
  <a href="mailto:varada.vinodnambiar@gmail.com">varada.vinodnambiar@gmail.com</a>
  <br>
  <a href="https://www.linkedin.com/in/varadanambiar/">LinkedIn Profile</a>
theme: jekyll-theme-minimal
