title: Varada Nambiar # your name (or website title) here
logo: "/circle_office.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
 Software Developer || Structural Engineer
  <br><br>
  <a href="mailto:varada.vinodnambiar@gmail.com">varada.vinodnambiar@gmail.com</a>
  <br>
  <a href="https://www.linkedin.com/in/varadanambiar/">LinkedIn Profile</a>
  <br>
  <a href="https://theinterviewportal.com/2021/12/18/structural-engineering-software-professional-interview/"> Interview Portal Article</a>
theme: jekyll-theme-minimal
